app.py
from flask import Flask
from config.config import Config
from web.routes import web

app = Flask(__name__)
app.config.from_object(Config)
app.register_blueprint(web)

if __name__ == '__main__':
    app.run()

web/controllers.py
import sys
from domain.services import SessionService, LoginService, UploadService, SignatureService
from config.config import Config
from flask import redirect, url_for, render_template, session, flash

class SessionController:

    def __init__(self, session_service: SessionService):
        self.session_service = session_service

    def new_session(self):
        self.session_service.session_init()

class LoginController:

    def __init__(self, login_service: LoginService):
        self.login_service = login_service

    def login(self, request):
        code = request.args.get('code')
        if code:
            resp_status = self.login_service.login(code)
            if resp_status == 200:
                return redirect(url_for('web.index'))
            else:
                return redirect(url_for('web.index'))
        return redirect(Config.RHSSO_LOGIN_URL)

    def logout(self, request):
        logout_url = self.login_service.logout()
        return redirect(logout_url)

class BusinessController:

    def business(self):
        if not 'id_token' in session or not session['id_token']:
            return redirect(url_for('web.index'))
        else:
            messages = None
            return render_template('pages/svempresa.html', messages=messages)

class ProccessController:

    def proccess(self):
        messages = None
        if not 'id_token' in session or not session['id_token']:
            return redirect(url_for('web.index'))
        elif not session['level']:
            flash('É necessária uma conta nível Prata ou Ouro para esta ação.', 'error')
            return redirect(url_for('web.business'))
        else:
            return render_template('pages/processo.html', messages=messages)

class UploadController:

    def __init__(self, upload_service: UploadService):
        self.upload_service = upload_service

    def upload(self, request):
        if not 'id_token' in session or not session['id_token']:
            return redirect(url_for('web.index'))
        else:
            if 'fileToUpload' not in request.files:
                return redirect(url_for('web.proccess'))
            self.upload_service.upload(request)
            if session['hashes']:
                return redirect(url_for('web.to_sign'))
            else:
                messages = json.dumps({"error":"Falha no upload. tente novamente."})
                flash('Falha no upload. tente novamente.', 'error')
                return redirect(url_for('web.proccess', messages=json.loads(messages)))

class SignatureController:

    def __init__(self, signature_service: SignatureService):
        self.signature_service = signature_service

    def to_sign(self, request):
        code = request.args.get('code')
        if code:
            token = self.signature_service.sign_token(code)
            if isinstance(token, str):
                cert = self.signature_service.get_cert(token)
                self.signature_service.sign_file(token)
                if session['doc_signed']:
                    flash('Operação executada com sucesso', 'success')
                    return redirect(url_for('web.business'))
                else:
                    flash('Falha na assinatura. tente novamente.', 'error')
                    return redirect(url_for('web.business'))
            elif token == 401:
                flash('Falha na assinatura. tente novamente.', 'error')
                return redirect(url_for('web.business'))
            else:
                flash('Falha no upload. tente novamente.', 'error')
                return redirect(url_for('web.business'))
        return redirect(Config.SIGNATURE_LOGIN_URL)

web/routes.py
from flask import Blueprint, render_template, request
from .controllers import LoginController, SessionController, ProccessController, \
BusinessController, UploadController, SignatureController
from domain.services import LoginService, SessionService, UploadService, \
SignatureService

web = Blueprint('web', __name__)

login_service = LoginService()
login_controller = LoginController(login_service)
session_service = SessionService()
session_controller = SessionController(session_service)
proccess_controller = ProccessController()
business_controller = BusinessController()
upload_service = UploadService()
upload_controller = UploadController(upload_service)
signature_service = SignatureService()
signature_controller = SignatureController(signature_service)

@web.route('/')
def index():
    session_controller.new_session()
    return render_template('pages/home.html')

@web.route('/login', methods=['GET', 'POST'])
def login():
    return login_controller.login(request)

@web.route('/logout', methods=['POST'])
def logout():
    return login_controller.logout(request)

@web.route('/svempresa')
def business():
    # session_controller.new_session()
    return business_controller.business()

@web.route('/processo')
def proccess():
    return proccess_controller.proccess()

@web.route('/upload', methods=['POST'])
def upload():
    return upload_controller.upload(request)

@web.route('/assinar', methods=['GET', 'POST'])
def to_sign():
    return signature_controller.to_sign(request)

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/tema-rjgov.css') }}" rel="stylesheet">
        <title>
            {% block title %}My Website{% endblock title %}
        </title>
    </head>

    <body class="container-pagina">
        {% block header %}{% endblock header %}
        <nav>
            <!-- Navigation Links -->
        </nav>

        <main class="min-vh-100 min-vw-100">
            {% block content %}{% endblock content %}
        </main>

        {% block footer %}{% endblock footer %}

    </body>

</html>

templates/pages/home.html
{% extends "layout/common.html" %}

<!-- home.tera -->
{% block title %}LABPRODERJ | INÍCIO{% endblock title %}

{% block content %}
<div class="portal-busca">
    <div class="portal56 portal282 portal2741">
        <h3 class="portal-busca-titulo">O que você procura?</h3>
        <form
            style="max-width: 720px; border-radius: 4px; width: 100%; justify-content: center; align-items: center; margin: 0px 20px; background-color: rgba(255, 255, 255, 0.85);">
            <div class="portal2732 row align-items-center">
                <div class="portal56 portal283 portal2733 col-1 px-4">
                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24"
                        class="portal-search-icon" height="1em" width="1em"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M19.023 16.977a35.13 35.13 0 0 1-1.367-1.384c-.372-.378-.596-.653-.596-.653l-2.8-1.337A6.962 6.962 0 0 0 16 9c0-3.859-3.14-7-7-7S2 5.141 2 9s3.14 7 7 7c1.763 0 3.37-.66 4.603-1.739l1.337 2.8s.275.224.653.596c.387.363.896.854 1.384 1.367l1.358 1.392.604.646 2.121-2.121-.646-.604c-.379-.372-.885-.866-1.391-1.36zM9 14c-2.757 0-5-2.243-5-5s2.243-5 5-5 5 2.243 5 5-2.243 5-5 5z">
                        </path>
                    </svg>
                </div>
                <div class="col-7">
                    <input class="portal-search-input" placeholder="Exemplo: IPVA, Portal do Servidor.."
                        value="">
                </div>
                <div class="col-2">
                    <button class="portal-search-btn" tabindex="0" type="submit">
                        <span class="portal77">
                            <p class="portal87 portal2738 portal89">Buscar</p>
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="portal56 portal2207 portal2743 m-4">
    <div class="portal56 portal2208">
        <div class="portal56 portal2209 portal2756">
            <h5 class="portal87 portal2752 portal96">Serviços em destaque</h5>
        </div>
        <div class="row">
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/educacao.svg') }}" alt="icon_servico">
                <div class="portal56 portal2211 portal2754 portal-card-body p-4">
                    <div style="text-align: center; width: 100%;">
                        <a class="portal-card-link"
                            href="/cidadao/servicos/educacao-e-pesquisa/categoria/9">Educação e Pesquisa</a>
                    </div>
                    <a class="portal-card-link" href="/servico/acessar-boletim-online190">&gt; Acessar
                        Boletim Online</a>
                </div>
            </div>
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/veiculo.svg') }}" alt="icon_servico">
                <div class="portal56 portal2212 portal2754 portal-card-body p-4">
                    <div style="text-align: center; width: 100%;">
                        <a class="portal-card-link"
                            href="/cidadao/servicos/veiculos-e-condutores/categoria/23">Veículos e
                            Condutores</a>
                    </div>
                    <a class="portal-card-link" href="/servico/acessar-ipva-grd134">&gt; Acessar IPVA /
                        GRD</a>
                </div>
            </div>
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/seguranca.svg') }}" alt="icon_servico">
                <div class="portal-card-body p-4">
                    <div style="text-align: center; width: 100%;">
                        <a class="portal-card-link"
                            href="/cidadao/servicos/seguranca-publica/categoria/19">Segurança Pública</a>
                    </div>
                    <a class="portal-card-link" href="/servico/fazer-registro-online-de-crime72">&gt; Fazer
                        registro online de crime</a>
                    <a class="portal-card-link"
                        href="/servico/fazer-o-boletim-de-registro-de-acidente-de-transito-sem-vitimas-e-brat159">&gt;
                        Fazer o Boletim de Registro de Acidente de Trânsito sem Vítimas (e-Brat)</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/cidadania.svg') }}" alt="icon_servico">
                <div class="portal-card-body p-4">
                    <div style="text-align: center; width: 100%;"><a class="portal-card-link"
                            href="/cidadao/servicos/cidadania-e-direitos/categoria/4">Cidadania e
                            Direitos</a></div><a class="portal-card-link"
                        href="/servico/reclamar-no-procon-online3">&gt; Reclamar no Procon online</a><a
                        class="portal-card-link" href="/servico/cadastrar-usuario-externo-sei-rj30">&gt;
                        Cadastrar
                        usuário externo SEI-RJ</a><a class="portal-card-link"
                        href="/servico/comunicar-violencia-domestica-contra-a-mulher86">&gt; Comunicar
                        Violência Doméstica contra a Mulher</a>
                </div>
            </div>
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/cidadania.svg') }}" alt="icon_servico">
                <div class="portal-card-body p-4">
                    <div style="text-align: center; width: 100%;"><a class="portal-card-link"
                            href="/cidadao/servicos/gestao-de-pessoas/categoria/47">Gestão de Pessoas</a>
                    </div><a class="portal-card-link"
                        href="/servico/acessar-sispatri-declaracao-patrimonial-2023169">&gt; Acessar
                        SISPATRI - Declaração Patrimonial 2024</a>
                </div>
            </div>
            <div class="col portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px" src="{{ url_for('static', filename='img/agua.svg') }}"
                    alt="icon_servico">
                <div class="portal56 portal2216 portal2754 portal-card-body p-4">
                    <div style="text-align: center; width: 100%;"><a class="portal-card-link"
                            href="/cidadao/servicos/agua-luz-e-saneamento/categoria/2">Água, Luz e
                            Saneamento</a></div><a class="portal-card-link"
                        href="/servico/verificacao-metrologica-em-medidor-relogio-de-energia-eletrica133">&gt;
                        Verificar medidor (relógio) de energia elétrica - IPEM</a>
                </div>
            </div>
        </div>
        <!-- if usuario logado -->
        <div class="row">
            {% if session['id_token'] %}
            <div class="col-4 portal-card-header m-4">
                <img class="portal-card-icon" width="68px" height="64px"
                    src="{{ url_for('static', filename='img/empresa.svg') }}" alt="icon_servico">
                <div class="portal-card-body p-4">
                    <div style="text-align: center; width: 100%;">
                        <a class="portal-card-link"
                            href="/cidadao/servicos/cidadania-e-direitos/categoria/4">
                            Empresas
                        </a>
                    </div>
                    <a class="portal-card-link"
                        href="{{ url_for('web.business') }}">&gt; Abertura de Empresas
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/processo.html
{% extends "layout/common.html" %}

{% block title %}LABPRODERJ | EMPRESA | ASSINATURA{% endblock title %}

{% block content %}
<div class="container min-vh-100 min-vw-100">
    <main>
        <div class="container-fluid p-4">
            <h2>Processo de abertura de empresa XXXXX-2024</h2>
            <div class="alert alert-secondary m-4" role="alert">
                <p>Para a assinatura do documento é necessário uma conta Gov.br nível Prata ou Ouro.</p>
                <p>
                    Para saber mais acesse:
                    <a class="alert-link" rel="stylesheet" href="https://www.gov.br/governodigital/pt-br/identidade/conta-gov-br/niveis-da-conta-govbr" target="_blank">
                        Saiba mais sobre os níveis da conta gov.br
                    </a>
                </p>
            </div>
            {% if messages['error'] %}
            <div class="alert alert-danger m-4" role="alert">
                <p>A simple danger alert—check it out!</p>
                <p>{{ messages['error'] }}</p>
            </div>
            {% endif %}
            {% if session['level'] %}
            <div class="card m-4">
                <div class="card-header bg-radio text-white">
                    Faça o Upload do contrato social para a assinatura:
                </div>
                <div class="card-body">
                    <div class="row justify-content-center mt-4">
                        <div class="col-sm-6 border">
                            <form action="{{ url_for('web.upload') }}" method="post" enctype="multipart/form-data">
                                <div class="row pb-4 justify-content-center">
                                    <div class="col-sm-12">
                                        <div class="lead">Envie o arquivo para fazer a assinatura:</div>
                                    </div>
                                </div>
                                <div class="row pb-4 justify-content-center">
                                    <div class="col-sm-12">
                                        <label for="fileToUpload" class="form-label">Selecione o arquivo:</label>
                                        <input class="form-control form-control-sm" name="fileToUpload" id="fileToUpload" type="file" required />
                                    </div>
                                </div>
                                <div class="row pb-4 justify-content-center">
                                    <div class="col-sm-6">
                                        <input type="submit" class="btn bg-radio text-white btn-lg w-100" value="Assinar" name="submit">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="card-body">
                <div class="row justify-content-center mt-4">
                    <p>TESTE ELSE</p>
                </div>
            </div>
            {% endif %}
        </div>
    </main>
</div>
{% endblock content %}

templates/pages/svempresa.html
{% extends "layout/common.html" %}

<!-- home.tera -->
{% block title %}LABPRODERJ | SERVIÇOS EMPRESAS{% endblock title %}

{% block content %}
<div class="container-fluid p-4">
    <h2>Processo de abertura de empresa XXXXX-2024</h2>
    {% if not session['level'] %}
        <div class="alert alert-warning m-4" role="alert">
            <p>A sua conta Gov.br não tem o nível necessário. Veja as intruções abaixo:</p>
            <p>Para a assinatura do documento é necessário uma conta Gov.br nível Prata ou Ouro.</p>
            <p>CPF com situação cancelada, nula ou falecido na Receita Federal não permite uso da assinatura eletrônica digital.</p>
            <p>
                Para saber mais acesse:
                <a class="alert-link" rel="stylesheet" href="https://www.gov.br/governodigital/pt-br/identidade/conta-gov-br/niveis-da-conta-govbr" target="_blank">
                    Saiba mais sobre os níveis da conta gov.br
                </a>
            </p>
            <p>
                Para mudar o nível da sua conta acesse:
                <a class="alert-link" rel="stylesheet" href="https://sso.staging.acesso.gov.br/" target="_blank">
                    níveis da conta gov.br
                </a>
            </p>
        </div>
    {% endif %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                <div class="alert alert-success m-4" role="alert">
                    <p>{{ message }}</p>
                </div>
                {% elif category == 'error' %}
                <div class="alert alert-danger m-4" role="alert">
                    <p>{{ message }}</p>
                </div>
                {% else %}
                <div class="alert alert-secondary m-4" role="alert">
                    <p>{{ message }}</p>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="card m-4">
        <div class="card-header bg-radio text-white">
            Itens do Processo pendentes
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">item do pendente</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% if not session['doc_signed'] %}
                    <tr>
                        <th scope='row'>1</th>
                        <td>Enviar e assinar contrato social.</td>
                        <td>
                            {% if not session['level'] %}
                            <span class="badge bg-warning text-dark">É necessária uma conta nível Prata ou Ouro para esta ação</span>
                            {% else %}
                            <form action="{{ url_for('web.proccess') }}">
                                <input type='submit' class='btn bg-radio text-white' value='assinatura' name='submit'/>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <th scope='row'>1</th>
                        <td>Conclusão do Processo</td>
                        <td>
                            <span class='badge bg-warning text-dark'>Aguardar conclusão do proccesso</span>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card m-4">
        <div class="card-header bg-radio text-white">
            Itens do Processo
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">item</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Envio dos Dado(s) do Sócio(s).</td>
                        <td>
                            <span class="badge bg-success">concluído</span>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Anexar Documentos do(s) Sócio(s).</td>
                        <td>
                            <span class="badge bg-warning text-dark">Em Análise</span>
                        </td>
                    </tr>
                    {% if session['doc_signed'] %}
                    <tr>
                        <th scope='row'>3</th>
                        <td>Enviar e assinar contrato social.</td>
                        <td>
                            <span class='badge bg-warning text-dark'>Em Análise</span>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/welcome.html
<!DOCTYPE html>
<html>

    <head>
        <title>Welcome to Flask App</title>
    </head>

    <body>
        <h1>Welcome to Flask App</h1>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>

</html>